In [53]:

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [54]:
# Load the Dataset
df = pd.read_csv('Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [55]:
# Preprocess the Data
# Drop irrelevant column
df= df.drop(['RowNumber','CustomerId','Surname'],axis=1)
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [56]:
# Encode Categorical Variable
label_encoder_gender = LabelEncoder()
df['Gender'] = label_encoder_gender.fit_transform(df['Gender'])
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [57]:
# OneHot Encoding for the "Geography" column
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder_geo = OneHotEncoder()
geo_encode = one_hot_encoder_geo.fit_transform(df[['Geography']])
geo_encode

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [58]:
geo_encode.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [59]:
one_hot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [60]:
geo_encoded_df = pd.DataFrame(geo_encode.toarray(),columns=one_hot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [61]:
# Combine the One Hot encoder Column with the original dataset
df = pd.concat([df.drop('Geography',axis=1),geo_encoded_df],axis = 1)
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [62]:
# Save the encoder and Scaler
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)
with open('one_hot_encoder_geo.pkl','wb') as file:
    pickle.dump(one_hot_encoder_geo,file)

In [63]:
# Divide the data into dependent & independent features
X = df.drop('Exited',axis=1)
y = df['Exited']

In [64]:
# Spliting the data into training and testing sets
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.2,random_state=42)

In [65]:
X_train.shape,X_test.shape

((2000, 12), (8000, 12))

In [66]:
# Scaled the Features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [67]:
X_train

array([[-0.38381126, -1.12244688,  2.60786056, ...,  1.00400803,
        -0.57427105, -0.58350885],
       [-0.73723819, -1.12244688,  0.12136034, ..., -0.99600797,
         1.74133801, -0.58350885],
       [ 0.32304261,  0.89091075, -0.54808203, ...,  1.00400803,
        -0.57427105, -0.58350885],
       ...,
       [ 0.85318301, -1.12244688, -0.06990891, ...,  1.00400803,
        -0.57427105, -0.58350885],
       [ 0.14632915,  0.89091075,  0.40826421, ...,  1.00400803,
        -0.57427105, -0.58350885],
       [ 0.45817644,  0.89091075,  1.1733412 , ..., -0.99600797,
         1.74133801, -0.58350885]], shape=(2000, 12))

In [68]:
X_test

array([[-0.59170945,  0.89091075, -0.64371665, ..., -0.99600797,
         1.74133801, -0.58350885],
       [-0.31104689,  0.89091075,  0.40826421, ...,  1.00400803,
        -0.57427105, -0.58350885],
       [-0.5397349 , -1.12244688,  0.50389883, ..., -0.99600797,
        -0.57427105,  1.71377008],
       ...,
       [ 0.63488991,  0.89091075, -0.54808203, ..., -0.99600797,
        -0.57427105,  1.71377008],
       [ 0.47896626,  0.89091075, -0.35681278, ...,  1.00400803,
        -0.57427105, -0.58350885],
       [-1.39211751,  0.89091075, -0.45244741, ...,  1.00400803,
        -0.57427105, -0.58350885]], shape=(8000, 12))

In [69]:
# Save the encoder and Scaler
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [70]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [71]:
model = Sequential()

model.add(Dense(64,activation='relu',input_shape=(X_train.shape[1],)))  ## 1st Hidden Layers
model.add(Dense(32,activation='relu')) ## 2nd Hidden Layers
model.add(Dense(1,activation='sigmoid'))

c:\Users\piusd\miniconda3\envs\Churm\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [72]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [73]:
## Compile the model
opt = tf.keras.optimizers.Adam(learning_rate=0.01)
loss = tf.keras.losses.BinaryCrossentropy()

model.compile(optimizer=opt,loss=loss,metrics=['accuracy'])

In [74]:
# Set up Tensorboard 
log_dir = "log/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [75]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=13,restore_best_weights=True)

In [76]:
# Train the model   
history = model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks = [early_stopping_callback,tensorflow_callback]
)

Epoch 1/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.8195 - loss: 0.4450 - val_accuracy: 0.8249 - val_loss: 0.4101
Epoch 2/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.8405 - loss: 0.3909 - val_accuracy: 0.8472 - val_loss: 0.3789
Epoch 3/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.8490 - loss: 0.3638 - val_accuracy: 0.8400 - val_loss: 0.3823
Epoch 4/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.8530 - loss: 0.3489 - val_accuracy: 0.8489 - val_loss: 0.3755
Epoch 5/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.8545 - loss: 0.3461 - val_accuracy: 0.8495 - val_loss: 0.3771
Epoch 6/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.8620 - loss: 0.3401 - val_accuracy: 0.8484 - val_loss: 0.3814
Epoch 7/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.8655 - loss: 0.3272 - val_accuracy: 0.8491 - val_loss: 0.3824
Epoch 8/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8635 - loss: 0.3188 - val_accuracy: 0.8510 - val_loss: 0.3712
Epoch 9/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8660 - loss: 0.3204 - val_accuracy: 0.8370 - val_loss: 0.4121
Epoch 10/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.8690 - loss: 0.3141 - val_accuracy: 0.8486 - val_loss: 0.4055
Epoch 11/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.8720 - loss: 0.2970 - val_accuracy: 0.8436 - val_loss: 0.4043
Epoch 12/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.8745 - loss: 0.2968 - val_accuracy: 0.8435 - val_loss: 0.4043
Epoch 13/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.8740 - loss: 0.2923 - val_accuracy: 0.8426 - val_loss: 0.4306
Epoch 14/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.8765 - loss: 0.2945 - val_accuracy: 0.8395 - val_loss: 0.4126
Epoch 15/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.8840 - loss: 0.2777 - val_accuracy: 0.8316 - val_loss: 0.4450
Epoch 16/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.8840 - loss: 0.2758 - val_accuracy: 0.8399 - val_loss: 0.4366
Epoch 17/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.8920 - loss: 0.2631 - val_accuracy: 0.8378 - val_loss: 0.4452
Epoch 18/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.8950 - loss: 0.2449 - val_accuracy: 0.8381 - val_loss: 0.4521
Epoch 19/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.8935 - loss: 0.2457 - val_accuracy: 0.8341 - val_loss: 0.4832
Epoch 20/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8930 - loss: 0.2535 - val_accuracy: 0.8329 - val_loss: 0.4794
Epoch 21/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.9015 - loss: 0.2319 - val_accuracy: 0.8249 - val_loss: 0.5145

In [77]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [78]:
# Load Tensorboard Extension
%load_ext tensorboard
# !pip show tensorboard/
# import os
# os.system("pkill -f tensorboard")

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [79]:
%tensorboard --logdir log/fit

Reusing TensorBoard on port 6006 (pid 5968), started 0:01:23 ago. (Use '!kill 5968' to kill it.)