In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [3]:
# Drop unnecessary columns
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [4]:
# Label encoding for categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [6]:
# One-hot encoding for 'Geography'
one_hot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = one_hot_encoder_geo.fit_transform(data[['Geography']])
geo_encoded_df = pd.DataFrame(geo_encoded.toarray(), columns=one_hot_encoder_geo.get_feature_names_out(['Geography']))

In [7]:
# Conbine the one-hot encoded columns with the original dataframe
data = pd.concat([data.drop(['Geography'], axis=1), geo_encoded_df], axis=1)
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [8]:
# Split into Independent and Dependent variables
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [9]:
# Spliting the data into training and testing sets
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.2,random_state=42)

In [10]:
X_train.shape,X_test.shape

((2000, 12), (8000, 12))

In [11]:
# Scaled the Features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
X_train

array([[-0.38381126, -1.12244688,  2.60786056, ...,  1.00400803,
        -0.57427105, -0.58350885],
       [-0.73723819, -1.12244688,  0.12136034, ..., -0.99600797,
         1.74133801, -0.58350885],
       [ 0.32304261,  0.89091075, -0.54808203, ...,  1.00400803,
        -0.57427105, -0.58350885],
       ...,
       [ 0.85318301, -1.12244688, -0.06990891, ...,  1.00400803,
        -0.57427105, -0.58350885],
       [ 0.14632915,  0.89091075,  0.40826421, ...,  1.00400803,
        -0.57427105, -0.58350885],
       [ 0.45817644,  0.89091075,  1.1733412 , ..., -0.99600797,
         1.74133801, -0.58350885]], shape=(2000, 12))

In [13]:
X_test

array([[-0.59170945,  0.89091075, -0.64371665, ..., -0.99600797,
         1.74133801, -0.58350885],
       [-0.31104689,  0.89091075,  0.40826421, ...,  1.00400803,
        -0.57427105, -0.58350885],
       [-0.5397349 , -1.12244688,  0.50389883, ..., -0.99600797,
        -0.57427105,  1.71377008],
       ...,
       [ 0.63488991,  0.89091075, -0.54808203, ..., -0.99600797,
        -0.57427105,  1.71377008],
       [ 0.47896626,  0.89091075, -0.35681278, ...,  1.00400803,
        -0.57427105, -0.58350885],
       [-1.39211751,  0.89091075, -0.45244741, ...,  1.00400803,
        -0.57427105, -0.58350885]], shape=(8000, 12))

In [14]:
# Save the encoder and Scaler
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)
with open('one_hot_encoder_geo.pkl','wb') as file:
    pickle.dump(one_hot_encoder_geo,file)
# Save the encoder and Scaler
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

ANN REGRESSION PROBLEM

In [15]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [16]:
model = Sequential()

model.add(Dense(64,activation='relu',input_shape=(X_train.shape[1],)))  ## 1st Hidden Layers
model.add(Dense(32,activation='relu')) ## 2nd Hidden Layers
model.add(Dense(1)) ## Output Layer

c:\Users\piusd\miniconda3\envs\Churm\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [17]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
## Compile the model
opt = tf.keras.optimizers.Adam(learning_rate=0.01)
loss = tf.keras.losses.MeanAbsoluteError()

model.compile(optimizer=opt,loss=loss,metrics=['mae'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [27]:
# Set up Tensorboard 
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime
regression_log_dir = "regressionlogs/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=regression_log_dir,histogram_freq=1)

In [28]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=12,restore_best_weights=True)

In [29]:
# Train the model   
history = model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks = [early_stopping_callback,tensorflow_callback]
)

Epoch 1/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 48693.1914 - mae: 48693.1914 - val_loss: 50258.4336 - val_mae: 50258.4336
Epoch 2/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 48669.5039 - mae: 48669.5039 - val_loss: 50378.6094 - val_mae: 50378.6094
Epoch 3/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 48630.1758 - mae: 48630.1758 - val_loss: 50278.0938 - val_mae: 50278.0938
Epoch 4/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 48591.0703 - mae: 48591.0703 - val_loss: 50254.0273 - val_mae: 50254.0273
Epoch 5/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 48622.8945 - mae: 48622.8945 - val_loss: 50260.7109 - val_mae: 50260.7109
Epoch 6/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 48544.6797 - mae: 48544.6797 - val_loss: 50267.5078 - val_mae: 50267.5078
Epoch 7/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 48531.3047 - mae: 48531.3047 - val_loss: 50308.6523 - val_mae: 50308.6523
Epoch 8/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 48464.6445 - mae: 48464.6445 - val_loss: 50243.8086 - val_mae: 50243.8086
Epoch 9/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 48532.1914 - mae: 48532.1914 - val_loss: 50347.1680 - val_mae: 50347.1680
Epoch 10/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 48481.6992 - mae: 48481.6992 - val_loss: 50284.7109 - val_mae: 50284.7109
Epoch 11/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 48435.9766 - mae: 48435.9766 - val_loss: 50276.0430 - val_mae: 50276.0430
Epoch 12/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 48484.8516 - mae: 48484.8516 - val_loss: 50413.4766 - val_mae: 50413.4766
Epoch 13/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 48430.3516 - mae: 48430.3516 - val_loss: 50323.8672 - val_mae: 50323.8672
Epoch 14/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 48430.0000 - mae: 48430.0000 - val_loss: 50330.5156 - val_mae: 50330.5156
Epoch 15/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 48397.8789 - mae: 48397.8789 - val_loss: 50332.9258 - val_mae: 50332.9258
Epoch 16/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 48395.1484 - mae: 48395.1484 - val_loss: 50397.6094 - val_mae: 50397.6094
Epoch 17/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 48380.0352 - mae: 48380.0352 - val_loss: 50344.2266 - val_mae: 50344.2266
Epoch 18/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 48337.9414 - mae: 48337.9414 - val_loss: 50334.1328 - val_mae: 50334.1328
Epoch 19/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 48342.4023 - mae: 48342.4023 - val_loss: 50315.3281 - val_mae: 50315.3281
Epoch 20/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 48374.2773 - mae: 48374.2773 - val_loss: 50301.5352 - val_mae: 50301.5352

In [30]:
# Load Tensorboard Extension
%load_ext tensorboard
# !pip show tensorboard/
# import os
# os.system("pkill -f tensorboard")

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [32]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 8076), started 0:03:46 ago. (Use '!kill 8076' to kill it.)

In [33]:
# Evaluate the model
test_loss, test_mae = model.evaluate(X_test,y_test)
print(f"Test Loss: {test_loss}")
print(f"Test MAE: {test_mae}")

250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50243.8086 - mae: 50243.8086
Test Loss: 50243.80859375
Test MAE: 50243.80859375

In [34]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.